### ISSUE TITLE
Bug: Tray Publisher Editorial Simple fails on "Integrating Asset" due to no representation associated with the created shot

### ISSUE THREAD

**Issue by robin-ynput** [ynput/ayon-traypublisher#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

When publishing via Tray Publisher "Editorial Simple" to create new shots it errors with the _This is not your fault_ error.

Here's the log:
[publish-report-240820-13-44.json](https://github.com/user-attachments/files/16679710/publish-report-240820-13-44.json)

Which shows error:
![image](https://github.com/user-attachments/assets/cdc545f9-ab57-4308-91fa-74300d3838b2)

### Expected Behavior:

I'm not sure about this one, are the integrating tasks relevant when simply creating a shot ?

### Expected Behavior:

The current behavior properly detects and creates the sequence/shots properly, but I'm not sure what's the purpose of the `Integrate Asset` tasks afterwards. 

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. Create a Folder and a Task under a project
2. Open AYON traypublisher and select `Editorial Simple`
3. Use a simple .edl and media to trigger the creation
4. Run the publish

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
Traceback (most recent call last):
  File "C:\Users\robin\AppData\Local\Ynput\AYON\dependency_packages\ayon_2406251801_windows.zip\dependencies\pyblish\plugin.py", line 528, in __explicit_process
    runner(*args)
  File "C:\Users\robin\OneDrive\Bureau\dev_ayon\dev\ayon-core\client\ayon_core\plugins\publish\integrate.py", line 144, in process
    filtered_repres = self.filter_representations(instance)
  File "C:\Users\robin\OneDrive\Bureau\dev_ayon\dev\ayon-core\client\ayon_core\plugins\publish\integrate.py", line 181, in filter_representations
    raise KnownPublishError(
ayon_core.pipeline.publish.publish_plugins.KnownPublishError: Instance shot has no representations to integrate
```

### Addon Versions

ayon_core - 0.4.4
ayon-traypublisher - 0.2.6

**Comment by robin-ynput** [comment]
Note, from the work I've done on Resolve. It looks like a simple `instance.data["integrate"] = False` might be solution here.

**Comment by jakubjezek001** [comment]
It seems that this had been already implemented via this PR https://github.com/ynput/ayon-traypublisher/pull/12/files#diff-1e3df0c50f4abae18adefdc7ec6d59fed745cb0bcb251882f19ceedfc597d44bR135
